print('привет мир')
print(b'\xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82' .decode('utf8'))
print('привет' .encode())
print(3+(2/2))
print('приветы' [:2] + 'приветы'[4:])
print('kinggemrkgvjerm' [::-1])
print('car')
